# Generated by Django 6.1.1 on 2026-09-29 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_remove_institution_unique_institution_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('phone_masked', models.CharField(max_length=20)),
                ('password_hash', models.CharField(default='', editable=False, max_length=128)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '전화번호 신원',
                'verbose_name_plural': '전화번호 신원',
            },
        ),
        migrations.CreateModel(
            name='CenterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('phone_masked', models.CharField(max_length=20)),
                ('password_hash', models.CharField(default='', editable=False, max_length=128)),
                ('institution_name', models.CharField(max_length=200)),
                ('business_reg_no', models.CharField(blank=True, max_length=20)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_contacts', to='app.institution')),
            ],
            options={
                'verbose_name': '센터 담당자',
                'verbose_name_plural': '센터 담당자',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('full_time', '정규직'), ('contract', '계약직'), ('part_time', '파트타임'), ('freelance', '프리랜서/단기')], db_index=True, max_length=20)),
                ('work_start_date', models.DateField(blank=True, null=True)),
                ('work_end_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('normalized_region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('career_requirement', models.CharField(blank=True, max_length=100)),
                ('required_certifications', models.JSONField(blank=True, default=list)),
                ('pay_type', models.CharField(choices=[('annual', '연봉'), ('monthly', '월급'), ('hourly', '시급'), ('session', '회당')], default='monthly', max_length=10)),
                ('pay_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_negotiable', models.BooleanField(default=False)),
                ('headcount', models.PositiveSmallIntegerField(default=1)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('recruiting', '모집중'), ('closed', '마감'), ('completed', '완료')], db_index=True, default='recruiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='jobs.centercontact')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='app.canonicalsport')),
            ],
            options={
                'verbose_name': '일자리 공고',
                'verbose_name_plural': '일자리 공고',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_masked', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('certification_verified', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
                ('phone_identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.phoneidentity')),
            ],
            options={
                'verbose_name': '지원',
                'verbose_name_plural': '지원',
                'ordering': ['-applied_at'],
                'constraints': [models.UniqueConstraint(fields=('job_posting', 'phone_identity'), name='unique_job_application')],
            },
        ),
    ]
