# Generated by Django 6.1.1 on 2026-09-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work24FetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('work24', '고용24(워크넷)')], max_length=20, unique=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '외부 채용정보 갱신 상태',
                'verbose_name_plural': '외부 채용정보 갱신 상태',
            },
        ),
        migrations.CreateModel(
            name='ExternalJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('work24', '고용24(워크넷)')], default='work24', max_length=20)),
                ('external_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=200)),
                ('pay_text', models.CharField(blank=True, max_length=200)),
                ('career_text', models.CharField(blank=True, max_length=200)),
                ('region_text', models.CharField(blank=True, max_length=200)),
                ('period_text', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '외부 채용정보',
                'verbose_name_plural': '외부 채용정보',
                'ordering': ['-fetched_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_external_job_posting')],
            },
        ),
    ]
