# Generated by Django 6.1.1 on 2026-09-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitutes', '0002_centercontact_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='status',
            field=models.CharField(choices=[('recruiting', '모집중'), ('closed', '모집중단'), ('completed', '모집완료')], db_index=True, default='recruiting', max_length=20),
        ),
    ]
